ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.home.arpa
  path: /
  pathType: Prefix
  tls: true
  tlsSecret: wildcard-home-arpa
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

persistence:
  defaultClass: false 

defaultSettings:
  defaultDataPath: "/storage01"

settings:
  service:
    ui:
      type: "ClusterIP"
