apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-home-arpa
  namespace: kube-system
spec:
  secretName: wildcard-home-arpa
  issuerRef:
    name: home-arpa-ca
    kind: ClusterIssuer
  dnsNames:
    - "*.home.arpa"
    - "home.arpa"
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
